Repository percona/k8sps-docs, pull requests merged in 2024-03, with the labels that each got.

#61 K8SPS-337 add new design items
  _resource/overrides/.icons/percona/kubernetes.svg
  _resource/overrides/.icons/percona/logo.svg
  _resource/overrides/main.html
  _resource/overrides/partials/nav.html
  docs/css/design.css
  docs/css/percona.css
  docs/fonts/Poppins-Italic.ttf
  docs/fonts/Poppins-Light.ttf
  docs/fonts/Poppins-LightItalic.ttf
  docs/fonts/Poppins-Medium.ttf
  docs/fonts/Poppins-MediumItalic.ttf
  docs/fonts/Poppins-Regular.ttf
  docs/fonts/Poppins-SemiBold.ttf
  docs/fonts/Poppins-SemiBoldItalic.ttf
  mkdocs-base.yml
  mkdocs.yml
  snippets/services-banner.md
Labels: documentation

#62 Fix accidental slash in path
  docs/router-conf.md
Labels: hotfix

#63 CLOUD-841 add arrows to external links
  docs/ReleaseNotes/Kubernetes-Operator-for-PS-RN0.1.0.md
  docs/ReleaseNotes/Kubernetes-Operator-for-PS-RN0.2.0.md
  docs/ReleaseNotes/Kubernetes-Operator-for-PS-RN0.3.0.md
  docs/ReleaseNotes/Kubernetes-Operator-for-PS-RN0.4.0.md
  docs/ReleaseNotes/Kubernetes-Operator-for-PS-RN0.5.0.md
  docs/ReleaseNotes/Kubernetes-Operator-for-PS-RN0.6.0.md
  docs/System-Requirements.md
  docs/TLS.md
  docs/annotations.md
  docs/architecture.md
  docs/backups-ondemand.md
  docs/backups-restore.md
  docs/backups-storage.md
  docs/backups.md
  docs/constraints.md
  docs/copyright.md
  docs/debug-logs.md
  docs/debug.md
  docs/eks.md
  docs/expose.md
  docs/gke.md
  docs/haproxy-conf.md
  docs/helm.md
  docs/index.md
  docs/kubernetes.md
  docs/minikube.md
  docs/monitoring.md
  docs/operator.md
  docs/options.md
  docs/pause.md
  docs/router-conf.md
  docs/scaling.md
  docs/sidecar.md
  docs/telemetry.md
  docs/trademark-policy.md
  docs/update.md
  docs/users.md
  mkdocs-base.yml
Labels: documentation

#68 fix a number of absent copy-to-clipboard tweakers
  docs/backups-storage.md
  docs/haproxy-conf.md
  docs/update.md
Labels: documentation

#69 Update update.md
  docs/update.md
Labels: documentation

#64 K8SPS-277 Add topologySpreadConstraints
  docs/operator.md
Labels: documentation, pending release

#67 CLOUD-681 Fixed connectivity.txt and added it to install instructions
  docs/assets/fragments/connectivity.txt
  docs/eks.md
  docs/gke.md
  docs/kubernetes.md
  mkdocs-base.yml
Labels: documentation

#70 K8SPS-337 add quickstart and improve troubleshooting guides
  docs/architecture.md
  docs/backup-tutorial.md
  docs/connect.md
  docs/data-insert.md
  docs/debug.md
  docs/helm.md
  docs/kubectl.md
  docs/monitoring-tutorial.md
  docs/monitoring.md
  docs/operator.md
  docs/quickstart.md
  docs/router-conf.md
  docs/what-next.md
  mkdocs-base.yml
  snippets/monitor-db.md
Labels: documentation

#65 K8SPS-314 add RN for 0.7
  docs/ReleaseNotes/Kubernetes-Operator-for-PS-RN0.7.0.md
  docs/ReleaseNotes/index.md
  docs/System-Requirements.md
  docs/images.md
  docs/versions.md
  mkdocs-base.yml
Labels: documentation
